import { useState } from 'react';
import { EtsyListing } from '../types';
import { generateEtsyMetadata, generateEtsyImage } from '../services/geminiService';
import { jsPDF } from "jspdf";

export const useStudio = () => {
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState<'idle' | 'metadata' | 'image' | 'complete'>('idle');
  const [listing, setListing] = useState<EtsyListing | null>(null);
  const [error, setError] = useState('');

  const createProduct = async (idea: string) => {
    if (!idea.trim()) return;
    
    setLoading(true);
    setStep('metadata');
    setError('');
    setListing(null);

    try {
      // 1. Generate Metadata
      const meta = await generateEtsyMetadata(idea);
      setListing(meta);
      
      // 2. Generate Image
      setStep('image');
      const imageBase64 = await generateEtsyImage(meta.imagePrompt);
      
      setListing(prev => prev ? { ...prev, imageBase64 } : null);
      setStep('complete');

    } catch (err: any) {
      console.error("Studio error:", err);
      setError(err.message || "Product creation failed.");
    } finally {
      setLoading(false);
    }
  };

  const updateListing = (updates: Partial<EtsyListing>) => {
    if (!listing) return;
    setListing({ ...listing, ...updates });
  };

  const downloadProductPack = (shopName: string = "NEXUS CREATIVE") => {
    if (!listing || !listing.imageBase64) return;

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);

      // Helper for centered text
      const centerText = (text: string, y: number) => {
        const textWidth = doc.getStringUnitWidth(text) * doc.getFontSize() / doc.internal.scaleFactor;
        const x = (pageWidth - textWidth) / 2;
        doc.text(text, x, y);
      };

      // ==========================================
      // PAGE 1: SELLER MANIFEST (INTERNAL USE)
      // ==========================================
      
      // Header Bar
      doc.setFillColor(236, 72, 153); // Nexus Pink
      doc.rect(0, 0, pageWidth, 30, 'F');
      
      doc.setFontSize(22);
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.text("SELLER STRATEGY MANIFEST", margin, 20);
      
      doc.setFontSize(10);
      doc.text("GENERATED BY NEXUS 3 STUDIO", pageWidth - margin - 60, 20);

      // Section 1: Core SEO
      doc.setTextColor(0, 0, 0);
      let cursorY = 50;
      
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("1. OPTIMIZED TITLE", margin, cursorY);
      cursorY += 8;
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const titleLines = doc.splitTextToSize(listing.title, contentWidth);
      doc.text(titleLines, margin, cursorY);
      cursorY += (titleLines.length * 6) + 10;

      // Section 2: Pricing
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("2. PRICING STRATEGY", margin, cursorY);
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text(listing.price, margin + 60, cursorY);
      cursorY += 20;

      // Section 3: Tags
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("3. SEARCH TAGS (COPY ALL)", margin, cursorY);
      cursorY += 8;
      
      // Render tags as "chips" visually
      doc.setFontSize(10);
      doc.setFont("courier", "normal");
      const tagsString = listing.tags.join(", ");
      const tagLines = doc.splitTextToSize(tagsString, contentWidth);
      doc.text(tagLines, margin, cursorY);
      cursorY += (tagLines.length * 5) + 15;

      // Section 4: Description
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("4. LISTING DESCRIPTION", margin, cursorY);
      cursorY += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const descLines = doc.splitTextToSize(listing.description, contentWidth);
      doc.text(descLines, margin, cursorY);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      centerText("INTERNAL USE ONLY - DO NOT DISTRIBUTE THIS PAGE TO CUSTOMERS", pageHeight - 10);


      // ==========================================
      // PAGE 2: CUSTOMER WELCOME (THE COVER)
      // ==========================================
      doc.addPage();
      
      // Branding
      doc.setFontSize(30);
      doc.setTextColor(0);
      doc.setFont("times", "bold");
      centerText(shopName.toUpperCase(), 60);

      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      centerText("THANK YOU FOR YOUR PURCHASE", 75);

      // Preview Image (Small)
      doc.addImage(`data:image/jpeg;base64,${listing.imageBase64}`, 'JPEG', (pageWidth - 100)/2, 90, 100, 100);

      doc.setFontSize(14);
      doc.setTextColor(0);
      centerText("YOUR DIGITAL DOWNLOAD IS ENCLOSED", 210);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      centerText("Please scroll to the next page to access your high-resolution asset.", 220);


      // ==========================================
      // PAGE 3: THE ASSET (FULL PAGE)
      // ==========================================
      doc.addPage();
      
      // Maximize image size within margins
      doc.addImage(
        `data:image/jpeg;base64,${listing.imageBase64}`, 
        'JPEG', 
        10, 
        20, 
        pageWidth - 20, 
        pageWidth - 20 // Square aspect ratio
      );

      // Crop marks simulation (lines at corners)
      doc.setDrawColor(200);
      doc.line(5, 20, 15, 20); // Top Left
      doc.line(10, 15, 10, 25);
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      centerText("HIGH RESOLUTION DIGITAL PRINT FILE", pageHeight - 15);


      // ==========================================
      // PAGE 4: LICENSE AGREEMENT
      // ==========================================
      doc.addPage();

      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.setFont("helvetica", "bold");
      doc.text("LICENSE & TERMS OF USE", margin, 40);

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60);
      
      const terms = [
        "1. PERSONAL USE ONLY: This file is for personal use only. You may print it for yourself or as a gift.",
        "",
        "2. NO RESALE: You may not resell, redistribute, or share the digital file in any form.",
        "",
        "3. COPYRIGHT: All designs remain the copyright of " + shopName + ".",
        "",
        "4. PRINTING: Colors may vary slightly depending on your monitor and printer settings. For best results, use high-quality cardstock or professional printing services.",
        "",
        "Thank you for supporting independent creators!"
      ];

      cursorY = 60;
      terms.forEach(line => {
        const lines = doc.splitTextToSize(line, contentWidth);
        doc.text(lines, margin, cursorY);
        cursorY += (lines.length * 6) + 4;
      });

      // Save
      const filename = listing.title.substring(0, 20).replace(/[^a-z0-9]/gi, '_') + "_ProductPack.pdf";
      doc.save(filename);

    } catch (e) {
      console.error("PDF generation failed", e);
      setError("Failed to generate PDF pack.");
    }
  };

  const reset = () => {
    setListing(null);
    setStep('idle');
    setError('');
  };

  return {
    loading,
    step,
    listing,
    error,
    createProduct,
    updateListing,
    downloadProductPack,
    reset
  };
};